spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://planbe-db.c3eaees6c18e.ap-northeast-2.rds.amazonaws.com/planbe
    username: superbe
    password: planbe123#

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
  use-fqn: true