server:
  servlet:
    application-display-name: superbe
  port: 8025

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://planbe-db.c3eaees6c18e.ap-northeast-2.rds.amazonaws.com/planbe
    username: superbe
    password: planbe123#
    hikari:
      connection-test-query: select 1 from dual
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
jwt:
  secretKey: fjkapnodsflvnsdavkhwiensejdnvasknavevnksnddkvfndlsk
