server:
  servlet:
    application-display-name: superbe
  port: 8025

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/superbe
    username: root
    password: 12345678
    hikari:
      connection-test-query: select 1 from dual
